apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: notes
          image: {{ .Values.image | quote }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: notes-config
            - secretRef:
                name: notes-db
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            timeoutSeconds: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
          volumeMounts:
            - name: ca
              mountPath: /etc/postgresql
              readOnly: true
      volumes:
        - name: ca
          configMap:
            name: postgres-ca
