apiVersion: v1
kind: Service
metadata:
  name: notes
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: notes
  ports:
    - name: http
      port: 80
      targetPort: 8000
